apiVersion: v1
kind: ConfigMap
metadata:
  name: miubot-config
  namespace: miubot
data:
  MIU_BOT_BACKEND__TYPE: "postgres"
  MIU_BOT_GATEWAY__HOST: "0.0.0.0"
  MIU_BOT_GATEWAY__PORT: "18790"
  MIU_BOT_AGENTS__DEFAULTS__MODEL: "anthropic/claude-opus-4-5"
